# Generated by Django 3.1.4 on 2020-12-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201220_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_az',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='disc_type_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Discount type'),
        ),
        migrations.AddField(
            model_name='product',
            name='disc_type_az',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Discount type'),
        ),
        migrations.AddField(
            model_name='product',
            name='disc_type_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Discount type'),
        ),
        migrations.AddField(
            model_name='product',
            name='disc_type_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Discount type'),
        ),
        migrations.AddField(
            model_name='product',
            name='disc_type_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Discount type'),
        ),
        migrations.AddField(
            model_name='product',
            name='disc_type_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Discount type'),
        ),
        migrations.AddField(
            model_name='product',
            name='disc_value_ar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount value'),
        ),
        migrations.AddField(
            model_name='product',
            name='disc_value_az',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount value'),
        ),
        migrations.AddField(
            model_name='product',
            name='disc_value_en',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount value'),
        ),
        migrations.AddField(
            model_name='product',
            name='disc_value_it',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount value'),
        ),
        migrations.AddField(
            model_name='product',
            name='disc_value_ru',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount value'),
        ),
        migrations.AddField(
            model_name='product',
            name='disc_value_tr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount value'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_size_ar',
            field=models.BooleanField(default=True, verbose_name='has_size'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_size_az',
            field=models.BooleanField(default=True, verbose_name='has_size'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_size_en',
            field=models.BooleanField(default=True, verbose_name='has_size'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_size_it',
            field=models.BooleanField(default=True, verbose_name='has_size'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_size_ru',
            field=models.BooleanField(default=True, verbose_name='has_size'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_size_tr',
            field=models.BooleanField(default=True, verbose_name='has_size'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ar',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_az',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_en',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_it',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ru',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_tr',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='Prodcut code'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code_az',
            field=models.CharField(max_length=50, null=True, verbose_name='Prodcut code'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Prodcut code'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code_it',
            field=models.CharField(max_length=50, null=True, verbose_name='Prodcut code'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Prodcut code'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code_tr',
            field=models.CharField(max_length=50, null=True, verbose_name='Prodcut code'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pattern_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pattern_az',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pattern_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pattern_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pattern_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pattern_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count_ar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sales Count'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count_az',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sales Count'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count_en',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sales Count'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count_it',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sales Count'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count_ru',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sales Count'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count_tr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sales Count'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ar',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_az',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_it',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tr',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='producimage',
            name='image',
            field=models.ImageField(upload_to='product_images', verbose_name='Resim'),
        ),
    ]
