# Generated by Django 3.1.4 on 2020-12-26 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201226_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProducImage',
            new_name='ProductImage',
        ),
    ]
