# Generated by Django 3.1.4 on 2020-12-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201227_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_it',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_pattern_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_pattern_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_pattern_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_pattern_it',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_pattern_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_pattern_tr',
        ),
    ]
