# Generated by Django 3.1.4 on 2020-12-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201227_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_az',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pattern_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pattern_az',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pattern_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pattern_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pattern_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pattern_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pattern'),
        ),
    ]
