# Generated by Django 3.1.4 on 2020-12-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20201228_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_ar',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_az',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_it',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tr',
            field=models.CharField(max_length=127, null=True, verbose_name='Title'),
        ),
    ]
