# Generated by Django 3.1.4 on 2021-01-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20201228_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=110, unique=True, verbose_name='Slug'),
        ),
    ]
