# Generated by Django 3.1.4 on 2020-12-20 13:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80, verbose_name='Name and Surname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-poçt')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon nömrəsi')),
                ('theme_title', models.IntegerField(choices=[(1, 'Online Alışveriş'), (2, 'Ürün Bilgisi'), (3, 'Sipariş & Ödeme İşlemleri'), (4, 'Öneri ve Şikayet'), (5, 'Teşekkür')], verbose_name='Choices Category')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
