# Generated by Django 3.1.4 on 2020-12-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('icon', models.CharField(max_length=50, verbose_name='Icons Class')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'SaleAdvantage',
                'verbose_name_plural': 'SaleAdvantages',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slide_images', verbose_name='Şəkil')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, related_name='slides', to='menu.Menu')),
                ('product', models.ManyToManyField(blank=True, related_name='slides', to='product.Product')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.CreateModel(
            name='Compaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='compaign title')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='positon in page')),
                ('small_image', models.ImageField(blank=True, null=True, upload_to='compaigns_title', verbose_name='Small image')),
                ('big_image', models.ImageField(blank=True, null=True, upload_to='compaigns_title', verbose_name='Big image')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, related_name='compaigns', to='menu.Menu')),
                ('product', models.ManyToManyField(blank=True, related_name='compaigns', to='product.Product')),
            ],
            options={
                'verbose_name': 'Compaign',
                'verbose_name_plural': 'Compaigns',
            },
        ),
    ]
