# Generated by Django 3.1.4 on 2020-12-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compaign',
            name='position',
        ),
        migrations.AddField(
            model_name='compaign',
            name='is_slide',
            field=models.BooleanField(default=False, verbose_name='Is Slide'),
        ),
        migrations.AddField(
            model_name='compaign',
            name='pos_choice',
            field=models.CharField(choices=[('up', 'up'), ('middle', 'middle'), ('down', 'down'), ('none', 'none')], default='none', max_length=50, verbose_name='positon choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compaign',
            name='rel_choice',
            field=models.CharField(choices=[('prod', 'product'), ('cat', 'category'), ('url', 'url'), ('none', 'none')], default='none', max_length=50, verbose_name='related choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compaign',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
