# Generated by Django 3.1.4 on 2020-12-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201220_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='up_image',
            field=models.ImageField(blank=True, null=True, upload_to='compaigns_title', verbose_name='Up image'),
        ),
    ]
