# Generated by Django 3.1.4 on 2020-12-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20201222_1522'),
        ('index', '0003_compaign_up_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compaign',
            name='big_image',
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='is_slide',
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='pos_choice',
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='product',
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='rel_choice',
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='small_image',
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='title',
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='up_image',
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='url',
        ),
        migrations.AddField(
            model_name='compaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='compaigns_images', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='compaign',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sırala'),
        ),
        migrations.AddField(
            model_name='compaign',
            name='position',
            field=models.CharField(choices=[('slider', 'slider'), ('second_section', 'second_section'), ('third_section', 'third_section'), ('baner', 'baner'), ('fourth', 'fourth')], default='baner', max_length=50, verbose_name='position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compaign',
            name='sm_image',
            field=models.ImageField(blank=True, null=True, upload_to='compaigns_images', verbose_name='Image sm'),
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='category',
        ),
        migrations.AddField(
            model_name='compaign',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compaigns', to='menu.menu'),
        ),
    ]
