# Generated by Django 3.1.4 on 2020-12-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20201222_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL link'),
        ),
    ]
