# Generated by Django 3.1.4 on 2020-12-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_compaign_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='compaigns_images', verbose_name='image lg'),
        ),
    ]
