# Generated by Django 3.1.4 on 2020-12-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20201225_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
    ]
