# Generated by Django 3.1.4 on 2021-01-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.CharField(max_length=40, unique=True, verbose_name='E-posta'),
        ),
    ]
