# Generated by Django 3.1.4 on 2020-12-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images', verbose_name='Categroy image')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('is_products', models.BooleanField(default=False, verbose_name='is porducts')),
                ('is_head', models.BooleanField(default=False, verbose_name='Is main')),
                ('is_new_season', models.BooleanField(default=False, verbose_name='New Season')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_categories', to='menu.menu')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
