# Generated by Django 3.1.4 on 2020-12-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='show_up',
            field=models.BooleanField(default=False, verbose_name='Shop Up'),
        ),
    ]
