# Generated by Django 3.1.4 on 2020-12-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_show_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='show_up',
            field=models.BooleanField(default=False, verbose_name='Show Up'),
        ),
    ]
